# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alberto Gómez-Martín
title: Ingeniero de Localización y Software
email: agomezmartinpro@gmail.com
teléfono: +34 665042685
website: https://agomezmartin.github.io/

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  agomezmartin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: albertogomezmartin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mi
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs

    Español de nacimiento, he vivido en Londres durante más de una década, ciudad en la que realicé mis estudios superiores y el principio de mi vida profesional. Soy Ingeniero de Localización y Software con formación previa en el sector educativo, tras trabajar en 2014 para <mark>Grupo MT</mark> y otras instituciones británicas como profesor de lengua inglesa y español respectivamente. Gracias a estas experiencias vi la importancia de la gestión de proyectos educativos y de una enseñanza innovadora y personalizada.

    A lo largo de mi carrera profesional, he desarrollado habilidades técnicas y de <mark>gestión de proyectos</mark> trabajando en diversos entornos, desde el sector de la localización hasta el desarrollo de software. Sin embargo, mi pasión por la educación y el crecimiento personal de los estudiantes me ha llevado a buscar una oportunidad para regresar al ámbito educativo. Estoy motivado por la posibilidad de gestionar proyectos que contribuyan al aprendizaje de una forma divertida y dinámica, tal como lo hacía cuando colaboré con <mark>Grupo MT</mark> en 2014.

    Mi enfoque profesional está centrado en la <mark>gestión de equipos y proyectos</mark>, y poseo una visión integral del trabajo colaborativo en entornos de aprendizaje. Estoy particularmente interesado en esta oportunidad dentro de un equipo innovador y comprometido con el desarrollo de actividades educativas que potencien el aprendizaje de los alumnos.

content:

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

#    EXPERIENCIA

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

  - title: Experiencia # Título de la sección
    layout: list # Tipo de contenido (lista/texto)
    content:

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: Replant
#        link: https://inforyde.com/
#        link_text: inforyde.com
        sub_title: Desarrollador Web y Cofundador
        caption: Diciembre 2024 - En la actualidad</br><mark>Madrid, España</mark> 
      #  quote: >

        description: | # this will include new lines to allow paragraphs

          Desarrollo y mantenimiento de la plataforma web de Replant, una startup dedicada a la venta de plantas de interior. 
          Utilizo tecnologías como Angular, TypeScript y bases de datos SQL desde Wordpress para crear una experiencia de usuario intuitiva y eficiente.
          
            - Angular
            - TypeScript
            - HTML/CSS
            - SQL
            
          Implementación de funcionalidades interactivas y optimización del rendimiento del sitio web para mejorar la experiencia del usuario.

      - layout: left
        title: Inforyde
        link: https://inforyde.com/
        link_text: inforyde.com
        sub_title: Ingeniero de Software Junior
        caption: Enero 2024 - Novimebre 2024</br><mark>Madrid, España</mark> 
      #  quote: >

        description: | # this will include new lines to allow paragraphs

          Diseño, desarrollo y mantenimiento de soluciones de software para herramientas energéticas.
          Contribuyo a la definición de productos y servicios futuros basados en C# y VBA.
          
            - Entity Framework
            - LINQ
            - ADO
            
          Control de versiones con Git y GitHub en la línea de comandos de Windows. Solicitudes de tickets en Jira.

      - layout: left
        title: ACOLAD
        link: https://www.acolad.com/
        link_text: acolad.com
        sub_title: Líder de Servicios Técnicos | Ingeniero de Localización
        caption: Septiembre 2018 - Septiembre 2021</br><mark>Madrid, España</mark> 
      #  quote: >

        description: | # this will include new lines to allow paragraphs
          
          <mark>Gestión técnica de proyectos</mark>
            - Evaluación y análisis desde el punto de vista técnico de los productos de los clientes.
            - Presupuestos
            - Gestión técnica de proveedores y documentación en Confluence

          <mark>Ingeniería de Localización</mark>
            - Preparación de archivos para procesamiento en CAT
            - Creación de parsers usando expresiones regulares
            - Segmentación
            - Migraciones
            - Gestión de Memorias de Traducción
            - Scripting

      - layout: left
        title: Transperfect
        link: https://www.transperfect.com/
        link_text: transperfect.com
        sub_title: Ingeniero de Localización
        caption: Madrid, España
        caption: Mayo 2015 - Agosto 2018</br><mark>Madrid y Barcelona</mark>, España 
#        quote: >

        description: | # this will include new lines to allow paragraphs

          Como parte del equipo de ingeniería de localización, éramos responsables de recibir los productos de los clientes, evaluar su idoneidad para el procesamiento de localización y elaborar presupuestos.
          <mark>Segmentación</mark> y <mark>desarrollo de parsers</mark> fueron tareas fundamentales de nuestro trabajo diario.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: Grupo MT
        link: https://www.mtgrupo.com/
        link_text: mtgrupo.com
        sub_title: Profesor de inglés e inmersiones lingüísticas
        caption: Febrero 2014 - Octubre 2014</br><mark>Madrid, España</mark> 
#        quote: >

        description: | # this will include new lines to allow paragraphs
            Durante mi tiempo en Grupo MT, tuve la oportunidad de continuar desarrollando mis habilidades lingüísticas y pedagógicas al impartir clases particulares de inglés a estudiantes de los primeros cursos de primaria.

      - layout: left
        title: GAMESYS LIMITED
        link: https://www.gamesysgroup.com/
        link_text: gamesysgroup.com
        sub_title: Traductor y localizador
        caption: Abril 2013 - Octubre 2014</br><mark>Londres, Reino Unido</mark> 
#        quote: >

        description: | # this will include new lines to allow paragraphs
            Durante mi tiempo en Gamesys, participé en la <mark>traducción y localización</mark> de su proyecto de videojuego en línea <mark>HotShot Trader</mark>. El videojuego en línea estaba basado en JavaScript e internacionalizado mediante la extracción de cadenas a archivos en formato JSON.
            Esta fue una oportunidad increíble para tener mi primer contacto profesional con proyectos reales de software mientras salía de la universidad.

      - layout: left
        title: The London Oratory School
        link: https://www.london-oratory.org/
        link_text: london-oratory.org
        sub_title: Asistente de Lengua Española
        caption: Octubre 2014 - Mayo 2015</br><mark>Londres, Reino Unido</mark> 
#        quote: >

        description: | # this will include new lines to allow paragraphs
            Asistente de conversación y preparador de exámenes orales de acceso a la universidad (A Levels).

      - layout: left
        title: Lady Margaret School
        link: https://ladymargaret.lbhf.sch.uk/
        link_text: ladymargaret.lbhf.sch.uk<br/>
        sub_title: Asistente de Lengua Española
        caption: Octubre 2014 - Mayo 2015</br><mark>Londres, Reino Unido</mark> 
#        quote: >

        description: | # this will include new lines to allow paragraphs
            Asistente de conversación y preparador de exámenes orales de acceso a la universidad (A Levels).

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

#    EDUCACIÓN

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

  - title: Educación # Título de la sección
    layout: list # Tipo de contenido (lista/texto)
    content:

      - layout: left
        title: Imperial College London
        caption: Octubre 2012 - Septiembre 2013</br><mark>Londres, Reino Unido</mark> 
        sub_title: MSc Traducción Científica, Médica y Técnica con Tecnología de la Traducción
        description: | # this will include new lines to allow paragraphs
          Durante mi tiempo en Imperial College London (ICL) adquirí habilidades técnicas específicas de mi campo relacionadas con <mark>tecnología de la traducción</mark>.
          
          Gestión de proyectos, herramientas de traducción asistida por ordenador (CAT) o Traducción Automática fueron algunos de los temas que se conectaron más estrechamente con el mundo profesional.

      - layout: left
        title: Imperial College London
        caption: Abril 2013 - Julio 2013</br><mark>Londres, Reino Unido</mark> 
        sub_title: Certificado en Localización de Software
        description: | # this will include new lines to allow paragraphs
          Este certificado en <mark>Localización de Software</mark> proporcionó conocimientos técnicos específicos sobre los procesos involucrados en la identificación y manejo de textos a extraer y localizar desde productos de software.

      - layout: left
        title: University of Westminster
        caption: Septiembre 2009 - Mayo 2012</br><mark>Londres, Reino Unido</mark> 
        sub_title: Grado en Traducción (Español-Inglés)
        description: | # this will include new lines to allow paragraphs
          El realizar un Grado en Traducción en la Universidad de Westminster me permitió desarrollar no solo habilidades de traducción directa e indirecta, sino también estudios sobre conciencia intercultural.

      - layout: left
        title: CRN
        caption: Septiembre 2023 - Noviembre 2023</br><mark>Madrid, España</mark> 
        sub_title: Java Proffesional Standard Edition (Certificado ORACLE)
        description: | # this will include new lines to allow paragraphs
          Java Standard Edition: el curso cubre el API de J2SE e incluye una preparación de 10 horas para el programa <mark>Oracle Certified Professional, Java SE</mark>. 

      - layout: left
        title: Centro de Formación en Tecnologías de la Información y las Comunicaciones de Madrid
        caption: Mayo 2023 - Julio 2023</br><mark>Madrid, España</mark> 
        sub_title: Desarrollo y visualización de datos con Python (Django y Pandas)
        description: | # this will include new lines to allow paragraphs
          Este <mark>curso intensivo</mark> se adentró en el mundo de la visualización de datos usando Python con un enfoque en el marco <mark>Django</mark>.

          - Django
          - Python
          - SQL
          - Pandas

      - layout: left
        title: Core Networks School
        caption: Septiembre 2022 - Noviembre 2022</br><mark>Madrid, España</mark> 
        sub_title: JAVA Enterprise Edition
        description: | # this will include new lines to allow paragraphs
          Uso de JAVA Enterprise Edition para desarrollar aplicaciones basadas en la web.

          - Java
          - SQL
          - Angular
          - Servicios

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

#    PROYECTOS

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

  - title: Proyectos # Título de la sección
    layout: list # Tipo de contenido (lista/texto)
    content:

      - layout: top-middle
        title: Repositorio de Internacionalización en GitHub
        link: github.com/agomezmartin/internationalization
        link_text: https://github.com/agomezmartin/internationalization
        additional_links:
          - title:  agomezmartin/internationalization
            icon: fab fa-github
            url: https://github.com/agomezmartin/internationalization
        description: | # this will include new lines to allow paragraphs
          Me apasiona explorar los diferentes enfoques para <mark>internacionalizar</mark> el contenido de software, por lo que decidí realizar un seguimiento de las estrategias con las que me encuentro, para tenerlas a mano en tareas cotidianas.
          Al tener el repositorio público, estaría orgulloso de que fuera útil para otros profesionales.

      - layout: top-middle
        title: Aplicación Django - CRUD
        link: github.com/agomezmartin/
        link_text: https://github.com/agomezmartin/internationalization/tree/main/assets/_projects/django/CRUD_i18n
        additional_links:
          - title:  agomezmartin
            icon: fab fa-github
            url: https://github.com/agomezmartin/internationalization/tree/main/assets/_projects/django/CRUD_i18n
        description: | # this will include new lines to allow paragraphs
          Comencé este proyecto como una forma de aprender <mark>Django</mark> y realizar operaciones <mark>CRUD</mark> usando el marco. He aprendido muchas habilidades con esto y me siento muy orgulloso de tenerlo en mi portafolio.

      - layout: top-middle
        title: Aplicación Django - DB (creación de cliente)
        link: github.com/agomezmartin/
        link_text: https://github.com/agomezmartin/internationalization/tree/main/assets/_projects/django/WebSite_MODAL_FORM_DB_i18n
        additional_links:
          - title:  agomezmartin
            icon: fab fa-github
            url: https://github.com/agomezmartin/internationalization/tree/main/assets/_projects/django/WebSite_MODAL_FORM_DB_i18n
        description: | # this will include new lines to allow paragraphs
          Comencé este proyecto como una forma de aprender <mark>Django</mark>, manejar formularios y <mark>bases de datos</mark>. He aprendido muchas habilidades con esto y me siento muy orgulloso de tenerlo en mi portafolio.

  - title: Software y Tecnología
    layout: text
    content: | # this will include new lines to allow paragraphs

      <img src="/images/memoq.png" width="20%" height="20%" style="margin-bottom:5%">
      <img src="/images/sdl.png" width="20%" height="20%" style="margin-bottom:5%">
      <img src="/images/XTM.png" width="20%" height="10%" style="margin-bottom:5%">
      <img src="/images/articulate.png" width="10%" height="10%" style="margin-left:5%;margin-right:5%;margin-bottom:5%">
      <img src="/images/i18n.png" width="10%" height="10%" style="margin-bottom:5%">
      <img src="/images/total_commander.png" width="10%" height="10%" style="margin-right:5%; margin-bottom:5%">
      <img src="/images/emeditor.png" width="20%" height="10%" style="margin-bottom:5%">
      <img src="/images/regex.jpeg" width="20%" height="10%" style="margin-bottom:5%">
      <img src="/images/django.png" width="20%" height="20%" style="margin-bottom:5%">
      <img src="/images/mysql.png" width="20%" height="10%" style="margin-bottom:5%">
      <img src="/images/bootstrap.png" width="10%" height="10%" style="margin-right:5%; margin-bottom:5%">
      <img src="/images/angular.png" width="20%" height="10%" style="margin-bottom:5%">
      <img src="/images/rest_api.png" width="20%" height="10%" style="margin-bottom:5%">
      <img src="/images/linux.png" width="10%" height="10%" style="margin-right:5%; margin-bottom:5%">
      <img src="/images/windows.png" width="10%" height="10%" style="margin-right:5%; margin-bottom:5%">
      <img src="/images/i18n.png" width="10%" height="10%" style="margin-right:5%; margin-bottom:5%">
      <img src="/images/l10n.png" width="20%" height="10%" style="margin-bottom:5%">
      <br>


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

  - title: Soft skills
    layout: text
    content: | # this will include new lines to allow paragraphs

      - Mente analítica
      - Gestión de proyectos ágiles y adaptación al cambio
      - Comunicación asertiva
      - Motivación para el aprendizaje
      - Mentorización y coaching
      - Enfoque centrado en el cliente
      - Responsabilidad

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

# Footer

footer_show_references: false
# references_title: Referencias bajo petición

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
